# Generated by Django 5.1.6 on 2025-02-13 06:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('procesador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador')),
                ('Tamano_pantalla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tamaño de pantalla')),
                ('altura', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Altura')),
                ('Largo', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Largo')),
                ('pais_origen', models.CharField(max_length=60, verbose_name='Pais de origen')),
                ('accesorios', models.CharField(max_length=400, verbose_name='Accesorios')),
                ('imagen', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images')),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='imgs')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
